#yaml 配置
services:
  #mysql-3307:
  #image: "mysql:8.0"
  #ports:
  #   - "3307:3307"
  # command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
  # environment:
  #   MYSQL_ROOT_PASSWORD: "644315"
  #   MYSQL_DATABASES: "go_test"
  #   MYSQL_PASSWORD: "644315"
  # volumes:
  #   - ./init.sql:/data/application/init.sql
  redis-6380:
    image: "redis:6.0"
    ports:
      - "6380:6380"
  testapp:
    build: .
    command: sh -c "./wait-for.sh mysql-3307:3307 redis-6380:6380 -- ./testapp"
    depends_on:
      #    - mysql-3307
      - redis-6380
    ports:
      - "8080:8081"
